#!/bin/bash
# Quick Build and Test Reference Card

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         EPON Manager Build & Test Quick Reference         ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║                                                            ║"
echo "║  Quick Start:                                              ║"
echo "║    ./build_and_test.sh              # Build and test all  ║"
echo "║    ./build_and_test.sh --clean      # Clean build + test  ║"
echo "║                                                            ║"
echo "║  Common Options:                                           ║"
echo "║    --unit-only         Unit tests only                     ║"
echo "║    --integration-only  Integration tests only              ║"
echo "║    --no-tests         Build without testing                ║"
echo "║    --verbose          Show detailed output                 ║"
echo "║    --help             Show full help                       ║"
echo "║                                                            ║"
echo "║  Manual Build:                                             ║"
echo "║    cd src/core && make              # Build application   ║"
echo "║    cd tests/unit && make test       # Run unit tests      ║"
echo "║                                                            ║"
echo "║  Test Coverage:                                            ║"
echo "║    ✓ Logger functionality                                  ║"
echo "║    ✓ Configuration management                              ║"
echo "║    ✓ Data structures (cache, queue, lists)                ║"
echo "║    ✓ Event processing flow                                 ║"
echo "║                                                            ║"
echo "║  Exit Codes:                                               ║"
echo "║    0 = All tests passed                                    ║"
echo "║    1 = Build failed or tests failed                        ║"
echo "║                                                            ║"
echo "║  Documentation:                                            ║"
echo "║    BUILD_AND_TEST_GUIDE.md  - Detailed guide               ║"
echo "║    README.md                - Project overview             ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
