# Makefile.am for include directory

# Public header files to install
pkginclude_HEADERS = \
    epon_hal.h \
    eponMgr_config.h \
    eponMgr_controller.h \
    eponMgr_hal_wrapper.h \
    eponMgr_logger.h \
    eponMgr_rbus.h \
    eponMgr_telemetry.h \
    eponMgr_tr181.h

# These headers are installed to $(includedir)/epon-manager/
pkgincludedir = $(includedir)/epon-manager
