# Makefile.am for hal_wrapper library

noinst_LIBRARIES = libeponMgr_hal_wrapper.a

libeponMgr_hal_wrapper_a_SOURCES = \
    eponMgr_hal_wrapper.c \
    eponMgr_hal_wrapper.h

libeponMgr_hal_wrapper_a_CFLAGS = \
    -I$(top_srcdir)/include \
    -I$(top_srcdir)/src/logger \
    -I$(top_srcdir)/src/core/data_structures \
    $(AM_CFLAGS)
